name: Build and Deploy to GitHub Pages

# Pemicu: Jalankan otomatisasi ini setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest # Menggunakan sistem operasi Ubuntu di server GitHub
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Menggunakan Node.js versi 18

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Project ğŸ—ï¸
        run: npm run build # Menjalankan skrip 'build' dari package.json

      - name: Deploy to GitHub Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Direktori yang akan di-publish (root folder proyek Anda)
